### ISSUE TITLE
Idempotency

### ISSUE THREAD

**Issue by tooolbox** [cenkalti/dalga#17]
It would be good to have a way for Dalga POSTs to be idempotent, meaning they contain some sort of information that allows a receiver to know "this is the Nth iteration of this job" irrespective of retries.

This could be as simple as taking the value of `next_sched` as a unix timestamp and including it as header or query param in the POST request.  If the receiver keeps records of jobs, and it receives a duplicate `next_sched` timestamp header, it can throw it away.  The header doesn't have to be called `next_sched`, it could be `iteration` or something.

**Comment by cenkalti** [comment]
Good idea. I prefer HTTP header over query parameter for POST requests. We can call the header as `dalga-next-sched`.
