### ISSUE TITLE
Releasing new version

### ISSUE THREAD

**Issue by cenkalti** [cenkalti/dalga#23]
@tooolbox I have made some changes after your PRs are merged. Do you have any objections about them? Or, do you want to make additional changes before releasing v3.0.0?

**Comment by tooolbox** [comment]
Hey @cenkalti thanks for pinging me.  I scanned through what you did and it all looks great.  I especially like the env var overrides and storing durations in textual representation (`60s`).

My one suggestion would be updating the README to reflect what Dalga is now capable of as of v3.  If I had the time I would take a stab at it but it would probably be at least a week until I could sit down and do that justice, so it's your call.

**Comment by cenkalti** [comment]
@tooolbox Thank you for your all contributions! 🍰
