### ISSUE TITLE
MariaDB Support

### ISSUE THREAD

**Issue by tooolbox** [cenkalti/dalga#5]
I typically run systems with MariaDB instead of MySQL.  This usually works out fine because the majority of syntax works across both system types.

In running the Dalga tests, I did encounter a problem with the `SKIP LOCKED` clause in `Front()` and found that MariaDB does not yet support this syntax.

1. Are you open to normalizing the SQL in this project to work across both systems?
2. If the performance improvement of things such as `SKIP LOCKED` are vital to you, would you be open to some sort of config or command-line flag to enable MariaDB compatibility?

**Comment by cenkalti** [comment]
`SKIP LOCKED` is a pure performance improvement. Without that, multiple instances of Dalga running on same jobs table would have to wait for each other and performance does not get increased by adding more instances. However, it is still good to run more that one instance for high availability.

We can add a config flag to disable using of `SKIP LOCKED` feature.

**Comment by tooolbox** [comment]
Makes sense.  Yes, the HA aspect is what I'm most concerned about.

Config flag sounds great.  Are you thinking `--no-skip-locked` or `--mariadb-compat`?  (One option is very specific, which is good, but the other can be used for any further incompatibilities that show up.)

**Comment by cenkalti** [comment]
I prefer `--no-skip-locked`. The `SKIP LOCKED` syntax has come with MySQL 8.0.1. With `--no-skip-locked`, Dalga can also be made compatible with older versions of MySQL.

Let's defer considering about `--mariadb-compat` flag if we encounter another incompatibility on the way.
